language: node_js

before_install:
  - npm install -g npm@latest

node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "stable"

script:
  - npm run lint
  - npm test

after_success:
  - npm run test:cov
  - npm run test:codecov
